import { Component, signal } from '@angular/core';
import { Payment } from './payments-table/payment';
import { PaymentsTable } from './payments-table/payments-table';

const INITIAL_PAYMENTS: readonly Payment[] = [
  {
    id: 'pay_3RxQZ9Jx7yL2kA4fB8mD',
    customer: 'olivia.martin@example.com',
    amount: 249,
    currency: 'USD',
    status: 'succeeded',
    paymentMethod: {
      kind: 'card',
      brand: 'visa',
      lastFour: '4242',
    },
    createdAt: '2026-07-13T14:48:00-03:00',
  },
  {
    id: 'pay_3RxQVuJx7yL2kA4fN6cP',
    customer: 'ethan.williams@example.com',
    amount: 89.5,
    currency: 'EUR',
    status: 'pending',
    paymentMethod: {
      kind: 'card',
      brand: 'mastercard',
      lastFour: '4444',
    },
    createdAt: '2026-07-13T14:42:00-03:00',
  },
  {
    id: 'pay_3RxQPnJx7yL2kA4fH2wS',
    customer: 'mia.thompson@example.co.uk',
    amount: 1240,
    currency: 'GBP',
    status: 'succeeded',
    paymentMethod: {
      kind: 'card',
      brand: 'amex',
      lastFour: '0005',
    },
    createdAt: '2026-07-13T14:33:00-03:00',
  },
  {
    id: 'pay_3RxQJcJx7yL2kA4fC9qT',
    customer: 'noah.bennett@example.com',
    amount: 64.99,
    currency: 'USD',
    status: 'failed',
    paymentMethod: {
      kind: 'card',
      brand: 'discover',
      lastFour: '0341',
    },
    createdAt: '2026-07-13T14:20:00-03:00',
  },
  {
    id: 'pay_3RxQERJx7yL2kA4fV5dM',
    customer: 'ava.patel@example.ca',
    amount: 318.2,
    currency: 'CAD',
    status: 'refunded',
    paymentMethod: {
      kind: 'card',
      brand: 'mastercard',
      wallet: 'apple-pay',
      lastFour: '9010',
    },
    createdAt: '2026-07-13T13:38:00-03:00',
  },
  {
    id: 'pay_3RxPzKJx7yL2kA4fR7bN',
    customer: 'liam.anderson@example.com',
    amount: 12840,
    currency: 'USD',
    status: 'succeeded',
    paymentMethod: {
      kind: 'standalone',
      method: 'ach',
      lastFour: '6789',
    },
    createdAt: '2026-07-13T12:51:00-03:00',
  },
  {
    id: 'pay_3RxPkTJx7yL2kA4fY1gW',
    customer: 'sophia.costa@example.com.br',
    amount: 729.9,
    currency: 'BRL',
    status: 'pending',
    paymentMethod: {
      kind: 'card',
      brand: 'visa',
      wallet: 'google-pay',
      lastFour: '5454',
    },
    createdAt: '2026-07-13T11:47:00-03:00',
  },
  {
    id: 'pay_3RxPNmJx7yL2kA4fK8sH',
    customer: 'lucas.miller@example.com',
    amount: 199,
    currency: 'USD',
    status: 'succeeded',
    paymentMethod: {
      kind: 'card',
      brand: 'amex',
      wallet: 'link',
      lastFour: '1881',
    },
    createdAt: '2026-07-13T09:55:00-03:00',
  },
  {
    id: 'pay_3RxPJeJx7yL2kA4fD3uC',
    customer: 'emma.schmidt@example.ch',
    amount: 415.75,
    currency: 'CHF',
    status: 'succeeded',
    paymentMethod: {
      kind: 'card',
      brand: 'diners-club',
      lastFour: '3055',
    },
    createdAt: '2026-07-13T09:27:00-03:00',
  },
  {
    id: 'pay_3RxPFaJx7yL2kA4fL9vQ',
    customer: 'haruto.sato@example.jp',
    amount: 18600,
    currency: 'JPY',
    status: 'pending',
    paymentMethod: {
      kind: 'card',
      brand: 'jcb',
      lastFour: '3530',
    },
    createdAt: '2026-07-13T08:44:00-03:00',
  },
  {
    id: 'pay_3RxPBWJx7yL2kA4fM2hR',
    customer: 'wei.zhang@example.cn',
    amount: 968,
    currency: 'CNY',
    status: 'failed',
    paymentMethod: {
      kind: 'card',
      brand: 'unionpay',
      lastFour: '6214',
    },
    createdAt: '2026-07-13T08:12:00-03:00',
  },
  {
    id: 'pay_3RxP7RJx7yL2kA4fE6nV',
    customer: 'lea.dupont@example.fr',
    amount: 540,
    currency: 'EUR',
    status: 'succeeded',
    paymentMethod: {
      kind: 'standalone',
      method: 'sepa',
      lastFour: '4821',
    },
    createdAt: '2026-07-13T07:36:00-03:00',
  },
  {
    id: 'pay_3RxP3NJx7yL2kA4fT8bK',
    customer: 'daan.devries@example.nl',
    amount: 72.45,
    currency: 'EUR',
    status: 'succeeded',
    paymentMethod: {
      kind: 'standalone',
      method: 'ideal',
    },
    createdAt: '2026-07-13T07:05:00-03:00',
  },
  {
    id: 'pay_3RxOzJJx7yL2kA4fP4sA',
    customer: 'elsa.lindberg@example.se',
    amount: 1195,
    currency: 'SEK',
    status: 'pending',
    paymentMethod: {
      kind: 'standalone',
      method: 'klarna',
    },
    createdAt: '2026-07-13T06:42:00-03:00',
  },
  {
    id: 'pay_3RxOvFJx7yL2kA4fG7mX',
    customer: 'charlotte.wilson@example.au',
    amount: 284.6,
    currency: 'AUD',
    status: 'refunded',
    paymentMethod: {
      kind: 'standalone',
      method: 'afterpay',
    },
    createdAt: '2026-07-13T05:58:00-03:00',
  },
  {
    id: 'pay_3RxOrBJx7yL2kA4fU1cD',
    customer: 'james.taylor@example.com',
    amount: 46.8,
    currency: 'USD',
    status: 'succeeded',
    paymentMethod: {
      kind: 'standalone',
      method: 'paypal',
    },
    createdAt: '2026-07-13T05:21:00-03:00',
  },
  {
    id: 'pay_3RxOn7Jx7yL2kA4fW5pL',
    customer: 'amelia.harris@example.com',
    amount: 35,
    currency: 'USD',
    status: 'succeeded',
    paymentMethod: {
      kind: 'standalone',
      method: 'cash-app-pay',
    },
    createdAt: '2026-07-13T04:43:00-03:00',
  },
  {
    id: 'pay_3RxOj3Jx7yL2kA4fZ9eN',
    customer: 'gabriel.silva@example.com.br',
    amount: 158.9,
    currency: 'BRL',
    status: 'succeeded',
    paymentMethod: {
      kind: 'standalone',
      method: 'pix',
    },
    createdAt: '2026-07-13T03:54:00-03:00',
  },
  {
    id: 'pay_3RxOfzJx7yL2kA4fQ2rS',
    customer: 'isabela.rocha@example.com.br',
    amount: 389.4,
    currency: 'BRL',
    status: 'pending',
    paymentMethod: {
      kind: 'standalone',
      method: 'boleto',
    },
    createdAt: '2026-07-13T02:47:00-03:00',
  },
  {
    id: 'pay_3RxObvJx7yL2kA4fI6tY',
    customer: 'mariana.souza@example.com.br',
    amount: 612,
    currency: 'BRL',
    status: 'failed',
    paymentMethod: {
      kind: 'card',
      brand: 'elo',
      lastFour: '5062',
    },
    createdAt: '2026-07-13T01:39:00-03:00',
  },
];

@Component({
  selector: 'app-root',
  imports: [PaymentsTable],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  protected readonly payments = signal(INITIAL_PAYMENTS);
}
